ODCServices.WebUi/Models/ConfigStorage/UIConfig.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using ODCServices.WebUi.Interfaces;

namespace ODCServices.WebUi.Models.ConfigStorage
{
	public class UiConfig
	{
		public Guid Id { get; set; }
		public string Name { get; set; }
		public string Version { get; set; }
		public DateTime Created { get; set; }
		public IFormFile File { get; set; }

		public Dictionary<UiConfigProperty, string> XmlProperties { get; set; }
		public Dictionary<UiConfigProperty, string> BuiltInProperties { get; set; }

		public static readonly List<string> BuiltInPropertiesList;

		static UiConfig()
		{
			BuiltInPropertiesList = new List<string>
			{
				nameof(Id),
				nameof(Name), 
				nameof(Version), 
				nameof(Created)
			};
		}

		public UiConfig()
		{
			XmlProperties = new Dictionary<UiConfigProperty, string>();

			BuiltInProperties = new Dictionary<UiConfigProperty, string>
			{
				{ new UiConfigProperty {Id = nameof(Id), DisplayName = nameof(Id), XmlPath = ""}, Id.ToString() },
				{ new UiConfigProperty {Id = nameof(Name), DisplayName = nameof(Name), XmlPath = ""}, Name },
				{ new UiConfigProperty {Id = nameof(Version), DisplayName = nameof(Version), XmlPath = ""}, Version },
				{ new UiConfigProperty {Id = nameof(Created), DisplayName = nameof(Created), XmlPath = ""}, Created.ToString() }
			};
		}

		public Dictionary<UiConfigProperty, string> GetAllProperties()
		{
			Dictionary<UiConfigProperty, string> result = new Dictionary<UiConfigProperty, string>(BuiltInProperties);

			foreach (KeyValuePair<UiConfigProperty, string> property in XmlProperties)
			{
				result.Add(property.Key, property.Value);
			}

			return result;
		}
	}
}

ODCServices.WebUi/Models/ConfigStorage/UiConfigProperty.cs
using ODCServices.WebUi.Interfaces;

namespace ODCServices.WebUi.Models.ConfigStorage
{
	public class UiConfigProperty
	{
		public string Id { get; set; }
		public string DisplayName { get; set; }
		public string XmlPath { get; set; }
	}
}

ODCServices.WebUi/Models/ErrorViewModel.cs
using System;

namespace ODCServices.WebUi.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ODCServices.WebUi/Controllers/ConfigStorageController.cs
using System;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ODCServices.ConfigStorage.Core.Interfaces;
using ODCServices.ConfigStorage.Core.Models;
using ODCServices.WebUi.Interfaces.Validators;
using ODCServices.WebUi.Models.ConfigStorage;
using ODCServices.WebUi.Validators;

namespace ODCServices.WebUi.Controllers
{
    public class ConfigStorageController : Controller
    {
		private readonly IConfigStorageService _configStorageService;

		private const string DATETIME_FORMAT = "d MMM yyyy";
		private readonly IMapper _mapper;

		public ConfigStorageController(IConfigStorageService configStorageService, IMapper mapper)
		{
			_mapper = mapper;
			_configStorageService = configStorageService;
		}

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAll()
        {
	        return Json(new
	        {
				builtInHeaders = UiConfig.BuiltInPropertiesList
					.Where(p => p != nameof(UiConfig.Id))
					.Select(item => new { id = item, name = item })
					.ToList(),
				headers = _configStorageService
					.GetAllProperties()
					.Select(prop => new
						{
							id = prop.Id, 
							name = prop.DisplayName
						})
					.ToList(),

				configs = _configStorageService
					.GetConfigs()
					.Select(coreConfig => _mapper.Map<UiConfig>(coreConfig))
					.Select(uiConfig => new
						{
							configId = uiConfig.Id,
							properties = uiConfig
								.GetAllProperties()
								.Where(p => p.Key.Id != nameof(UiConfig.Id))
								.Select(p => new { propId = p.Key.Id, propValue = p.Value })
								.ToList()
						})
					.ToList()
			});
        }

		public IActionResult Download(Guid configId)
        {
	        return Json(new
	        {
		        result = _configStorageService.GetConfigs().FirstOrDefault(c => c.Id == configId)
	        });
        }

		[HttpPost]
		public IActionResult AddNew(UiConfig newConfig)
		{
			IConfigValidator validator = new ConfigValidator();
			IValidationResult configValidationResult = validator.IsValid(newConfig);
			string jsonResult = "";
			if (configValidationResult.IsValid)
			{
				_configStorageService.AddNewConfig(_mapper.Map<CoreConfig>(newConfig));
				jsonResult = "success";
			}
			else
			{
				jsonResult = string.Join(" ", configValidationResult.ValidationErrors);
			}

			return Json(new { result = jsonResult });
		}

    }
}

ODCServices.WebUi/Controllers/ODCServicesController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ODCServices.PasswordObfuscator.Interfaces;
using ODCServices.WebUi.Models;

namespace ODCServices.WebUi.Controllers
{
	public class ODCServicesController : Controller
	{
		private readonly IPasswordObfuscatorService _passwordsService;

		public ODCServicesController(IPasswordObfuscatorService passwordsService)
		{
			_passwordsService = passwordsService;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult PasswordDecorder()
		{
			return View();
		}

		public IActionResult Obfuscate(string plainPassword)
		{
			string obfuscatedPassword = "";
			try
			{
				obfuscatedPassword = _passwordsService.Obfuscate(plainPassword);
			}
			catch (Exception)
			{
				return Json(new { result = "Error. Check the source string and try again." });
			}
			return Json(new { result = obfuscatedPassword });
		}

		public IActionResult DeObfuscate(string obfuscatedPassword)
		{
			string plainPassword = "";
			try
			{
				plainPassword = _passwordsService.DeObfuscate(obfuscatedPassword);
			}
			catch (Exception)
			{
				return Json(new { result = "Error. Check the source string and try again." });
			}
			return Json(new { result = plainPassword });
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ODCServices.WebUi/Views/ConfigStorage/Index.cshtml


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/ConfigStorage.css" />

<div id="configStorageAppContainer"></div>


<script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
<script src="dist/configStorage/configStorage.js"></script>

ODCServices.WebUi/Views/ODCSErvices/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
	<h1 class="display-4">ODC Services</h1>
</div>

ODCServices.WebUi/Views/ODCSErvices/PasswordDecorder.cshtml
@{
    ViewData["Title"] = "(De)Obfuscate password";
}

<link rel="stylesheet" href="~/css/PasswordDecorder.css" />

<div class="text-center">
	<h1 class="display-4">(De)Obfuscate password</h1>
	<input type="text" name="password"/>
	<p>
		<button onclick="obfuscatePassword()">Obfuscate</button>
		<button onclick="DeObfuscatePassword()">DeObfuscate</button>
	</p>
    <p name="result"></p>
</div>

<script src="~/js/PasswordDecorder.js" asp-append-version="true"></script>

ODCServices.WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ODC Services</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ODCServices" asp-action="Index">ODC Services</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="ODCServices" asp-action="PasswordDecorder">Obfuscate password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ConfigStorage" asp-action="Index">UiConfig Storage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">&copy; 2020 - ODC Services</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>